Django/lolRipMe/lolRipMe/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
    ]

Django/lolRipMe/pages/urls.py
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.about, name='home'),
    # path('about/', views.about, name='about'),
    path('login/', views.login, name='login'),
    path('read/', views.read, name='read'),
    path('text/', views.text, name='text'),
    path('upload/', views.model_form_upload, name='upload'),
    path('sidenav/', views.sidenav, name='sidenav'),
   ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/lolRipMe/pages/models.py
from django.db import models

class Document(models.Model):
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to='documents/')
    # upload = models.FileField(upload_to='documents/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

Django/lolRipMe/pages/templates/about.html
<!DOCTYPE html>
<html lang="en">

{% include 'base.html' %}


<div  style="text-align: center">
  <div class="jumbotron bg-cover">
    <div class="overlay"></div>
    <div class="container">
      <!-- <p class="lead"> <span>"Morton Technologies"</span></p> -->
      <h1 class="display-3 mb-1"><strong><font color="white">Morton Technologies</font></strong></h1></p>
      <br>
      <h2 class="display-3 mb-1"><strong><font color="white">Developing Software To Bring Every Mind To Its Fullist Potential</font></strong></h2></p>
    </div>
  </div>
</html>

Django/lolRipMe/pages/templates/base.html
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css"  href="/media/documents/main.css">
</head>

{% block content %}
{% endblock%}
  <body>

{%block header%}
{%endblock%}

<div class="header" id='sidenav'>
    <span style="color: orange;font-size:30px;cursor:pointer" onclick="openNav()">&#9776;Audio FIles</span>
    <div class="header-right">
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'read' %}">Reader</a>
      <a href="{% url 'upload' %}">Upload</a>
      <a href="http://localhost:8000/admin">Admin</a>

    </div>
</div>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    {% for file in download_list %}
    <a href="/media/processed-audio/{{file}}" download="{{file}}">{{file}}</a>
    {% endfor %}
</div>

<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "300px";
    }
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>

  </body>

Django/lolRipMe/pages/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Home</title>
  <!-- <link rel="icon" href="http://ipfs.io/ipfs/QmUinfhwmhbfZZd1L9dtP3bHtG9PBokPJThLu59DYE9s48/"> -->
</head>
<!-- Start bootstrap text -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<style type="text/css">
    /* Background image */
.jumbotron {
    text-align: center;
    padding-top: 10rem;
    padding-bottom: 10rem;
    text-shadow: 2px 2px #000;
}
.lead span {
    color: orange;
    font-weight: bold;
}
.bg-cover {
    background-image: url("/home/c/github/Text-to-Speech/Django/lolRipMe/media/web-images/Glass-Dom.jpeg");
    background-size: cover;
    color: white;
    background-position: center;
    position: relative;
    z-index: -2;
}
.overlay {
    background-color: #000;
    opacity: 0.31;
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    z-index: -1;
}
body {
    background-color: #282828;
    margin: 0px;
    font-family: "Lato", sans-serif;
}
.btn-circle {
    width: 30px;
    height: 30px;
    text-align: center;
    padding: 6px 0;
    font-size: 12px;
    line-height: 1.428571429;
    border-radius: 5px;
}
.btn-circle.btn-lg {
    width: 50px;
    height: 50px;
    padding: 10px 16px;
    font-size: 16px;
    line-height: 1.33;
    border-radius: 25px;
}
.btn-circle.btn-xl {
    width: 70px;
    height: 70px;
    padding: 10px 24px;
    font-size: 24px;
    line-height: 1.33;
    border-radius: 40px;
}
.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #fff;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}
.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
}
.sidenav a:hover {
    color: #f1f1f1;
}
.closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}
@media screen and (max-height: 450px) {
    .sidenav {
        padding-top: 15px;
    }
    .sidenav a {
        font-size: 18px;
    }
}
.header {
    overflow: hidden;
    background-color: #282828;
    padding: 20px 10px;
}
.header a {
    float: left;
    color: white;
    text-align: center;
    padding: 15px;
    text-decoration: none;
    font-size: 18px;
    line-height: 25px;
    border-radius: 20px;
}
.header a.logo {
    font-size: 25px;
    font-weight: bold;
}
.header a:hover {
    background-color: #ddd;
    color: black;
}
.header a.active {
    background-color: orange;
    color: white;
}
.header-right {
    float: right;
}
@media screen and (max-width: 500px) {
    .header a {
        float: none;
        display: block;
        text-align: left;
    }
    .header-right {
        float: none;
    }
}
.button {
    text-decoration: none;
    display: inline-block;
    height: 50px;
    background: orange;
    line-height: 50px;
    font-size: 25px;
    border-radius: 5px;
    color: #282828;
    text-align: center;
    width: 60%;
}
.button:hover {
    text-decoration: none;
    background-color: darkorange;
    color: #282828;
    cursor: pointer;
}
.presents{
    color: white;
}
</style>

<body>
<div class="header">
    <span style="color: orange;font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Channels</span>
    <div class="header-right">
      <a href="{% url 'home' %}">Home</a>
      <a href="{% url 'upload' %}">Upload</a>
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'about' %}">About</a>
      <a href="{% url 'read' %}">Reader</a>
        <a href="http://localhost:8000/admin">Admin</a>
    </div>
</div>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="">Bridge</a>
    <a href="">Reactor Room</a>
    <a href="">Lower Deck</a>
    <a href="">Navigation</a>
    <a href="">Helm</a>
    <a href="">Port</a>
    <a href="">Starboard</a>
    <a href="">Engineering</a>
    <a href="">Private Quarters 3B</a>
</div>


<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "300px";
    }
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>


<div class="jumbotron bg-cover">
    <div class="overlay"></div>
    <div class="container">
        <h1 class="display-3 mb-1"><big><strong>Morton Technologies</strong></big></h1>
        <br>
        <h2><strong><big>Presents</big></strong></h2>
    </div>
</div>
<div class="text-center presents">
    <h1>Text 2 Speech Suite</h1>
</div>
</body>

Django/lolRipMe/pages/templates/login.html
<!DOCTYPE html>
<html lang="en">

{% include 'base.html' %}


<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <title>Login</title>

</head>

  <div class="jumbotron bg-cover">
    <div class="overlay"></div>
    <div class="container">
      <h2 class="display-3 mb-1"><strong><font color="white">Developing Software To Bring Every Mind To Its Fullist Potential</font></strong></h2></p>
      <p class="lead"> <span></span></p>
    </div>
  </div>

        </div>
          <div class="col-md-2"></div>
      </form>
    </div>
  </div>
</body>
</html>

Django/lolRipMe/pages/templates/model_form_upload.html
{% include 'base.html' %}

<style>
input[type=file] {
  opacity: 0;
}

input[type=file]:hover {
  opacity: 0;

}

.btn {
  border-style: none;
    background-color: Transparent;
    float: left;
    color: white;
    text-align: center;
    padding: 15px;
    text-decoration: none;
    font-size: 25px;
    line-height: 25px;
    border-radius: 20px;
}

.btn:hover {
  background-color: #ddd;
  color: black;
}
</style>

<br><br><br><br><br><br><br><br><br><br><br>
<div class="col-md-4">
</div>
<div class="col-md-4" style="text-align: center">
        {% block content %}
        <form method="post" enctype="multipart/form-data">
          <label class="btn form-control input-lg">
        {{ form.as_p }}
        {% csrf_token %}
        </label>
        <br><br>
        <br><br>
      <button class="btn form-control input-lg" type="submit">Upload</button>
      </form>
        {% endblock %}
      </div>

Django/lolRipMe/pages/templates/profile.html
<html>
   <body>

      <form name = "form" enctype = "multipart/form-data"
         action = "{% url "myapp.views.SaveProfile" %}" method = "POST" >{% csrf_token %}

         <div style = "max-width:470px;">
            <center>
               <input type = "text" style = "margin-left:20%;"
               placeholder = "Name" name = "name" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>
               <input type = "file" style = "margin-left:20%;"
                  placeholder = "Picture" name = "picture" />
            </center>
         </div>

         <br>

         <div style = "max-width:470px;">
            <center>

               <button style = "border:0px;background-color:#4285F4; margin-top:8%;
                  height:35px; width:80%; margin-left:19%;" type = "submit" value = "Login" >
                  <strong>Login</strong>
               </button>

            </center>
         </div>

      </form>

   </body>
</html>

Django/lolRipMe/pages/templates/read.html
<!DOCTYPE html>
<html lang="en">
{% include 'base.html' %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Reader</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css"  href="/media/documents/main.css">
</head>

<style>
body {
  background-color: #606060;
  margin: 0px;
  font-family: "Lato", sans-serif;
  font-size: 15;
  font-weight: 750;
}
input[type=file] {
  opacity: 0;
}

input[type=file]:hover {
  opacity: 0;

}

.btn {
  border-style: none;
    background-color: Transparent;
    float: left;
    color: white;
    text-align: center;
    padding: 15px;
    text-decoration: none;
    font-size: 25px;
    line-height: 25px;
    border-radius: 20px;
}

.btn:hover {
  background-color: #ddd;
  color: black;
}

/*input[type=textarea] { width: 100vw; }*/
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>

<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "300px";

    }
    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
</script>

<body>

<br>
<div class="col-md-1">
</div>

<div id="text" class="form-group col-md-10">
<textarea class="form-control" id="text" rows="33">{% for phrase in file_content %}{{phrase}}{% endfor %}</textarea>
</div>
<div class="col-md-1">
</div>

<div class="col-md-12" style="text-align: center">
  <br>

  <div class="col-md-4" style="text-align: center">
      {% block content %}
        <form method="post" enctype="multipart/form-data">
          <label for="id_document" name="upload" class="btn form-control input-lg">lol</label>
            {{ form.as_p }}
            {% csrf_token %}
        </div>
          <div class="col-md-4" style="text-align: center">
          <audio src="" controls></audio>
        </div>
          <div class="col-md-4">
      <button class="btn form-control input-lg" type="submit">Upload</button>
    </form>
    {% endblock %}
    </div>
      </div>
</div>
</body>

Django/lolRipMe/pages/templates/sidebar.html
<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    {% for file in download_list %}
    <a href="/media/processed-audio/{{file}}" download="{{file}}">{{file}}</a>
    {% endfor %}
</div>

Django/lolRipMe/pages/templates/sidenav.html
<div id="sidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    {% for file in download_list %}
    <a href="/media/processed-audio/{{file}}" download="{{file}}">{{file}}</a>
    {% endfor %}
</div>

Django/lolRipMe/pages/templates/text.html
<div id="text" class="form-group">
<textarea class="form-control" id="text" rows="33">{% for phrase in file_content %}
  {{phrase}}
  {%endfor%}</textarea>
</div>